/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import beans.EThemeEvenement;
import beans.Evenement;
import beans.Intervenant;
import beans.ParticipationEvenement;
import services.EvenementService;
import services.IntervenantService;
import services.ParticipationEvenementService;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author HP-PC
 */
public class EvenementForm extends javax.swing.JInternalFrame {

    private IntervenantService is;
    private EvenementService es;
    private ParticipationEvenementService ps;
    private DefaultTableModel model;
    private static int id;

    /**
     * Creates new form EvenementForm
     */
    public EvenementForm() {
        initComponents();
        is = new IntervenantService();
        es = new EvenementService();
        
        model = (DefaultTableModel) evenementliste.getModel();
        load();

    }

    void load() {
        model.setRowCount(0);
        for (Evenement e : es.findAll()) {
            model.addRow(new Object[]{
                e.getId(),
                e.getTitre(),
                e.getTheme(),
                e.getDate(),
                e.getLieu(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        S = new javax.swing.JRadioButton();
        T = new javax.swing.JRadioButton();
        I = new javax.swing.JRadioButton();
        E = new javax.swing.JRadioButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtLieu = new javax.swing.JTextField();
        bnAdd = new javax.swing.JButton();
        bnUpdate = new javax.swing.JButton();
        bnDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        evenementliste = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFont(new java.awt.Font("Roboto Slab Medium", 0, 10)); // NOI18N
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(241, 243, 244));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gestoin des evenements", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/theme-icon-png-0 (1).jpg"))); // NOI18N
        jLabel1.setText("Theme :");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/date.png"))); // NOI18N
        jLabel2.setText("Date :");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/OIP (1) (1).jpeg"))); // NOI18N
        jLabel3.setText("Lieu :");

        buttonGroup1.add(S);
        S.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        S.setText("SCIENCE");

        buttonGroup1.add(T);
        T.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        T.setText("TECHNOLOGIE");

        buttonGroup1.add(I);
        I.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        I.setText("INNOVATION");

        buttonGroup1.add(E);
        E.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        E.setText("EDUCATION");

        txtDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtLieu.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtLieu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bnAdd.setBackground(new java.awt.Color(0, 200, 83));
        bnAdd.setForeground(new java.awt.Color(255, 255, 255));
        bnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/edit_add.png"))); // NOI18N
        bnAdd.setText("Ajouter");
        bnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAddActionPerformed(evt);
            }
        });

        bnUpdate.setBackground(new java.awt.Color(251, 192, 45));
        bnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/agt_update_recommended.png"))); // NOI18N
        bnUpdate.setText("Modifier");
        bnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnUpdateActionPerformed(evt);
            }
        });

        bnDelete.setBackground(new java.awt.Color(229, 57, 53));
        bnDelete.setForeground(new java.awt.Color(255, 255, 255));
        bnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/delete_user.png"))); // NOI18N
        bnDelete.setText("Supprimer");
        bnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDeleteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/R (1) (1).png"))); // NOI18N
        jLabel5.setText("Titre:");

        txtNom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bnDelete)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(S)
                        .addGap(24, 24, 24)
                        .addComponent(T))
                    .addComponent(txtLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(I)
                .addGap(18, 18, 18)
                .addComponent(E)
                .addGap(397, 397, 397))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(S)
                    .addComponent(T)
                    .addComponent(I)
                    .addComponent(E))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnUpdate)
                    .addComponent(bnDelete)
                    .addComponent(bnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Liste des evenements", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 3, 14))); // NOI18N

        evenementliste.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        evenementliste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Titre", "Theme", "Date", "Lieu"
            }
        ));
        evenementliste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evenementlisteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(evenementliste);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAddActionPerformed

         String titre = txtNom.getText().trim();
    Date date = txtDate.getDate();
    String lieu = txtLieu.getText().trim();
    EThemeEvenement theme = null;

    // Déterminer le thème sélectionné
    if (S.isSelected()) {
        theme = EThemeEvenement.SCIENCE;
    } else if (T.isSelected()) {
        theme = EThemeEvenement.TECHNOLOGIE;
    } else if (I.isSelected()) {
        theme = EThemeEvenement.INNOVATION;
    } else if (E.isSelected()) {
        theme = EThemeEvenement.EDUCATION;
    }

    // Vérification des champs obligatoires (sans intervenant)
    if (titre.isEmpty() || theme == null || date == null || lieu.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !");
        return;
    }

    // Créer l'événement
    Evenement evenement = new Evenement(titre, theme, date, lieu);

    // Liste vide d'intervenants au moment de l'ajout
    List<Intervenant> intervenants = new ArrayList<>();

    if (es.create(evenement, intervenants)) {
        JOptionPane.showMessageDialog(this, "✅ Événement bien enregistré !");
        load();
    } else {
        JOptionPane.showMessageDialog(this, "❌ Erreur lors de l'enregistrement de l'événement !");
    }

    }//GEN-LAST:event_bnAddActionPerformed

    private void evenementlisteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evenementlisteMouseClicked
        int selectedRow = evenementliste.getSelectedRow();

        if (selectedRow == -1) {
            return;
        }

        id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        txtNom.setText(model.getValueAt(selectedRow, 1).toString());
        txtLieu.setText(model.getValueAt(selectedRow, 4).toString());

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date = sdf.parse(model.getValueAt(selectedRow, 3).toString());
            txtDate.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur lors de la conversion de la date !");
        }

        String theme = model.getValueAt(selectedRow, 2).toString();
        if (theme.equalsIgnoreCase("SCIENCE")) {
            S.setSelected(true);
        } else if (theme.equalsIgnoreCase("TECHNOLOGIE")) {
            T.setSelected(true);
        } else if (theme.equalsIgnoreCase("INNOVATION")) {
            I.setSelected(true);
        } else if (theme.equalsIgnoreCase("EDUCATION")) {
            E.setSelected(true);
        }


      }//GEN-LAST:event_evenementlisteMouseClicked

    private void bnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDeleteActionPerformed
        int selectedRow = evenementliste.getSelectedRow(); // Récupérer la ligne sélectionnée

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un événement à supprimer !");
            return;
        }

        int response = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer cet événement ?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
            Evenement evenement = es.findById(id);

            if (evenement != null && es.delete(evenement)) {
                JOptionPane.showMessageDialog(this, "Événement supprimé avec succès !");
                load();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression !");
            }
        }
     }//GEN-LAST:event_bnDeleteActionPerformed

    private void bnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnUpdateActionPerformed

        int selectedRow = evenementliste.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un événement à modifier !");
            return;
        }

        int response = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier cet événement ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {

            int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
            String titre = txtNom.getText().trim();
            String lieu = txtLieu.getText().trim();
            Date date = txtDate.getDate();
            EThemeEvenement theme = null;

            if (S.isSelected()) {
                theme = EThemeEvenement.SCIENCE;
            } else if (T.isSelected()) {
                theme = EThemeEvenement.TECHNOLOGIE;
            } else if (I.isSelected()) {
                theme = EThemeEvenement.INNOVATION;
            } else if (E.isSelected()) {
                theme = EThemeEvenement.EDUCATION;
            }

            if (titre.isEmpty() || theme == null || date == null || lieu.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !");
                return;
            }

            // 🔄 Mise à jour sans intervenant
            Evenement evenement = new Evenement(id, titre, theme, date, lieu);
            if (es.update(evenement)) {
                JOptionPane.showMessageDialog(this, "Événement modifié avec succès !");
                load();
            } else {
                JOptionPane.showMessageDialog(this, "Problème lors de la mise à jour !");
            }
        }
    }//GEN-LAST:event_bnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton E;
    private javax.swing.JRadioButton I;
    private javax.swing.JRadioButton S;
    private javax.swing.JRadioButton T;
    private javax.swing.JButton bnAdd;
    private javax.swing.JButton bnDelete;
    private javax.swing.JButton bnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable evenementliste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtLieu;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
